name: "Build and Push Image"

on:
  push:
    branches:
      - main

jobs:
  build-image:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Build and Push
        run: |
          tag=$(date +%s)
          docker buildx use mybuilder
          # python cryptography does not support ARM v7, so we can only build arm64
          docker buildx build --platform linux/amd64,linux/arm64 -t romulusai/automation-runner:latest --push .
